"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var superHero = [];
superHero.push("Thor");
console.log(superHero);
var heroPower = [];
heroPower.push(7);
console.log(heroPower);
var users = [];
users.push({ name: "Joseph", isActive: true });
console.log(users);
